; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = 
	h2zero/NimBLE-Arduino@^2.3.4
	madhephaestus/ESP32Servo @ ^0.13.0
	knolleary/PubSubClient
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
	mbed-bxd/Adafruit_PWMServoDriver@0.0.0+sha.41a00db32ae7
